on:
  push:
    branches:    
      - blog
jobs:
  my-job:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@blog
    - name: Deploy
      run: |
        npm install && npm run deploy